import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Nabvar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CRUD Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='max-w-6xl mx-auto p-4'>

          <Navbar />
          <div className='mt-5'>
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
